name: Sync with Azure DevOps

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    steps:       
    - uses: actions/checkout@v3
    - uses: a11smiles/GitSync@main
      env:     
        ado_token: "{{sjumfpuzjvz7uopboc7etr55i7pvx4n2flxmz3z5afvw3np4zfoq}}"
        github_token: "{{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}}"
        ado_organization: "dynamicscrm"
        ado_project : "Solutions"
        ado_wit : "Issue from GH"
        ado_new_state : "New"
        ado_active_state : "Approved"
        ado_close_state : " Done"
        autoCreate": true
        assignedTo": "v-selvarajd@microsoft.com"
        areaPath": "Test2"
        "iterationPath": "Test2"
        ado_bypassrules : true
        
