name: Sync with Azure DevOps

on:
  schedule:
    - cron: '*/15 * * * *'
  issues:
    types: [opened, closed, deleted, reopened, edited, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Sync workflow
    steps:       
    - uses: actions/checkout@v3
    - uses: a11smiles/GitSync@main
      env:     
        ado_token: '${{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 }}'
        github_token: '${{ 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 }}'
        config_file: './.github/workflows/sync_config.json'
